// 'use client';
// import './global.css';

import ThemeProvider from '../lib/ThemeProvider';

export const metadata = {
  title: 'Hi from metadata',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
